#!/data/data/com.termux/files/usr/bin/bash
#set -x

HOME_LOC='/run/media/nowhereman/5c272246-9fa8-4671-a436-966b50f58f86/nowhereman'
PHONE_LOC='/storage/emulated/0'
while true
	do
		echo "                Welcome to Sync-All"
        echo "    To upload from Phone to Computer: Option 1"
        echo "   To Download to Phone from Computer: Option 2"
        echo "       x) To exit script: type x q X or exit"
		read -p "         Do you want to Upload or Download: " CHOICE
	case "$CHOICE" in
		1|upload)
			echo "    1)   All"
			echo "    2)   Camera"
    		echo "    3)   Downloads"
    		echo "    4)   Movies"
    		echo "    5)   Music"
			echo "    6)   PDF"
			echo "    7)   Pictures"
			echo ""
	 		read -p " Which would you like to do: " OPTION1
				case "$OPTION1" in
					1|all)
						rsync --ignore-existing -avz --progress $PHONE_LOC/{DCIM,Movies,Music,PDF,Pictures} home:$HOME_LOC
						rsync --ignore-existing -avz --progress $PHONE_LOC/Download/* home:$HOME_LOC/Downloads
						exit
						;;
					2|camera)
						rsync --ignore-existing -avz --progress $PHONE_LOC/DCIM home:$HOME_LOC
						exit
						;;
					3|downloads)
						rsync --ignore-existing -avz --progress $PHONE_LOC/Download/* home:$HOME_LOC/Downloads
						exit
						;;
					4|movies)
						rsync --ignore-existing -avz --progress $PHONE_LOC/Movies home:$HOME_LOC
						exit
						;;
					5|music)
						rsync --ignore-existing -avz --progress $PHONE_LOC/Music home:$HOME_LOC
						exit
						;;
					6|pdf)
						rsync --ignore-existing -avz --progress $PHONE_LOC/PDF home:$HOME_LOC
						exit
						;;
					7|pictures)
						rsync --ignore-existing -avz --progress $PHONE_LOC/Pictures home:$HOME_LOC
						exit
						;;
					*)
						echo "         Invalid choice! Exiting..."
						exit
						;;
				esac	;;
		2|download)
					echo "    1)   All"
					echo "    2)   Camera"
    			    echo "    3)   Downloads"
    			    echo "    4)   Movies"
    			    echo "    5)   Music"
					echo "    6)   PDF"
					echo "    7)   Pictures"
					echo ""
	 				read -p " Which would you like to do: " OPTION2
						case "$OPTION2" in
							1|all)
								rsync --ignore-existing -avz --progress home:$HOME_LOC/{DCIM,Movies,Music,PDF,Pictures} $PHONE_LOC
								rsync --ignore-existing -avz --progress home:$HOME_LOC/Downloads/* $PHONE_LOC/Download
								exit
								;;
							2|camera)
								rsync --ignore-existing -avz --progress home:$HOME_LOC/DCIM $PHONE_LOC
								exit
								;;
							3|downloads)
								rsync --ignore-existing -avz --progress home:$HOME_LOC/Downloads/* $PHONE_LOC/Download
								exit
								;;
							4|movies)
								rsync --ignore-existing -avz --progress home:$HOME_LOC/Movies $PHONE_LOC
								exit
								;;
							5|music)
								rsync --ignore-existing -avz --progress home:$HOME_LOC/Music $PHONE_LOC
								exit
								;;
							6|pdf)
								rsync --ignore-existing -avz --progress home:$HOME_LOC/PDF $PHONE_LOC
								exit
								;;
							7|pictures)
								rsync --ignore-existing -avz --progress home:$HOME_LOC/Pictures $PHONE_LOC
								exit
								;;
							*)
								echo "         Invalid choice! Exiting..."
								exit
								;;
				esac			;;
		x|X|exit|q)
			echo "                 Exiting..."
			exit
			;;
		*)
			echo "         Invalid choice! Exiting..."
			exit
			;;
	esac
done
